version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Check code style
          command: ./gradlew clean ktlintCheck --no-daemon